workflows:
  ios-build-only:
    name: iOS Build Only (No Signing)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --no-codesign

    artifacts:
      - build/ios/iphoneos/**
